# Generated by Django 4.1.13 on 2024-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='call',
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='driver_profile_pics/'),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='CallHistory',
        ),
    ]
