# Generated by Django 4.1.13 on 2024-05-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_message_hirerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ambulances',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
