# Generated by Django 4.1.13 on 2024-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_remove_driver_ambulances_ambulance_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ambulances',
            field=models.ManyToManyField(related_name='drivers', to='driver.ambulance'),
        ),
    ]
