# Generated by Django 4.1.13 on 2024-05-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_driver_ambulances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ambulances',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulances', to='driver.driver'),
        ),
    ]
