# Generated by Django 4.1.13 on 2024-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_alter_hirerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
